development:
  adapter:  postgresql
  #host:     localhost
  encoding: unicode
  database: akc_development
  pool:     5
  username: kirk
  password: sd3472307
  #template: template1

test:
  adapter:  postgresql
  #host:     localhost
  encoding: unicode
  database: akc_test
  pool:     5
  username: kirk
  password: sd3472307
  #template: template1
production:
  adapter:  postgresql
  #host:     localhost
  encoding: unicode
  database: akc_production
  pool:     5
  username: kirk
  password: sd3472307
  #template: template1